### ISSUE TITLE
[BUG] Panic Due to Integer Divide by Zero in

### ISSUE THREAD

**Issue by hedeqiang** [avascriptions/open-indexer#4]
panic: runtime error: integer divide by zero

token.max == 2100000000000000000
```
if token.Minted.Cmp(token.Max) >= 0 {
	token.Progress = 1000000
} else {
	token.Progress = int32(utils.ParseInt64(token.Minted.String()) * 1000000 / utils.ParseInt64(token.Max.String()))
}
```

**Comment by avascriptions** [comment]
Try to run it, it will not report an error, but it will cause the minted value to be incorrect and the index of this token to be incorrect, we will fix this.
